name: Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - run: echo "Finding all Java classes..."
      - run: dir /s /B *.java > sources.txt
      - run: javac @sources.txt
      - run: java -cp src/ com.group31.main.Main
